<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Main">
    <TargetFramework>netstandard2.1</TargetFramework>
    <NoWarn>CS1573;CS1587;CS1591;IDE0130</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Label="Package">
    <Version>0.0.1</Version>
    <Authors>DCoats</Authors>
    <Company>Functionairy</Company>
    <Copyright>Copyright (c) Functionairy 2025</Copyright>
    <Description>Functionairy overload types library.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/Functionairy/F10Y.L0038.git</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\F10Y.T0018\source\F10Y.T0018\F10Y.T0018.csproj" />
  </ItemGroup>
</Project>